config/routes.rb
Rails.application.routes.draw do
  get  'signup' => 'users#new'
  get  'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'
  resources :users
  resources :events
  resources :invites
  root 'sessions#new'
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates  :title,       presence: true
	validates  :description, presence: true
	validates  :date,        presence: true
	belongs_to :creator,     :class_name  => "User"
	has_many   :invites,     :foreign_key => :attended_event_id
	has_many   :attendees,   through:        :invites
	scope			 :upcoming,    -> { where('date >= ?', DateTime.now).order('Date ASC') }
	scope      :past,        -> { where('date < ?', DateTime.now).order('Date DESC') }

end

app/models/invite.rb
class Invite < ActiveRecord::Base
	belongs_to :attendee,       :class_name => "User"
	belongs_to :attended_event, :class_name => "Event"
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name,  presence: true
	validates :email, presence: true
	has_many :created_events,  :foreign_key => "creator_id", :class_name => "Event"
	has_many :invites,         :foreign_key => :attendee_id
	has_many :attended_events, through:        :invites

	def upcoming_events
		self.attended_events.where('date >= ?', DateTime.now)
	end

	def previous_events
		self.attended_events.where('date < ?', DateTime.now)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController


	def new
		@event = Event.new
	end

	def create
		@event = current_user.created_events.build(event_params)
		if @event.save
			flash[:success] = "You have created a new event!"
			redirect_to @event
		else
			flash.now[:danger] = "Invalid parameters."
			render 'new'
		end
	end


	def show
		@event = Event.find(params[:id])
		@attendees = @event.attendees.all
		@creator = @event.creator
	end

	def index
		@upcoming = Event.upcoming
		@past     = Event.past
	end

	private

	def event_params
		params.require(:event).permit(:title, :description, :date)
	end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

	def create
		@event = Event.find(params[:invite][:attended_event_id])
		current_user.invites.create(attended_event_id: @event.id)
		redirect_to current_user
	end

	def destroy
		@invite = Invite.find(params[:id])
		current_user.invites.destroy(@invite)
		redirect_to current_user
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(name: params[:session][:name])
		if user 
			flash[:success] = "You have successfully signed in."
			sign_in user
			
		else
			flash.now[:danger] = "User does not exist by that name."
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to signin_url
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success]    = "You have created a new User."
			sign_in @user
		else
			flash.now[:danger] = "Invalid parameters."
			render 'new'  
		end
	end

	def show
		@user            = User.find(params[:id])
		@created_events  = @user.created_events.all
		@upcoming_events = @user.attended_events.upcoming
		@prev_events     = @user.attended_events.past
	end

	def index
		@users = User.all
	end
	
	private

	def user_params
		params.require(:user).permit(:name, :email)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	attr_writer :current_user

	def sign_in(user)
		session[:user_id] = user.id
		@current_user = user
		redirect_to @current_user
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1> All Events </h1>
<h4>Upcoming</h4>
<%= render 'shared/table', object: @upcoming %>
<h4>Past</h4>
<%= render 'shared/table', object: @past %>

app/views/events/new.html.erb
<h1> Event Creation </h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<%= form_for(@event) do |f| %>
			<%= f.label :title %>
			<%= f.text_field :title %>

			<%= f.label :description %>
			<%= f.text_area :description %>

			<%= f.label :date %>
			<%= f.datetime_select :date, :order => [:month, :day, :year] %>

			<%= f.submit "Create Event", class: "btn btn-success"%>


		<% end %>
	</div>
</div>

app/views/events/show.html.erb
<h1><%= @event.title %> by <%= link_to "#{@creator.name}", user_path(@creator[:id]) %></h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
<% if @event.attendees.include?(current_user) %>
	<%= form_for(current_user.invites.find_by(attended_event_id: @event.id), :html => { :method => :delete }) do |f| %>
		<%= f.submit "Leave Event", class: "btn btn-danger" %>
	<% end %>


<% else %> 
	<%= form_for(current_user.invites.build(attended_event_id: @event.id)) do |f| %>
		  <%= f.hidden_field :attended_event_id, :value => @event.id %>
			<%= f.submit "Attend Event", class: "btn btn-success" %>
	<% end %>
<% end %>
<h2>		<%= @event.date.strftime("%B %d, %Y") %> at <%= @event.date.strftime("%I:%M %p") %>
</h2>
<h4> Additional Info </h4>
<h2> <%= @event.description %> <h2>


<h4> Attendees </h4>
<% if @attendees.empty? %> 
	<h2>None</h2>
<% else %>
	<% @attendees.each do |attendee| %>
	<h2>
		<%= link_to "#{attendee.name}", user_path(attendee[:id]) %>
	</h2>
	<% end %>
<% end %>
	</div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<% if signed_in? %>
		<nav>
			<ul class="nav navbar-nav navbar-left">
				<li><%= link_to "Create an Event!", new_event_path %></li>
			</ul>
			<ul class ="nav navbar-nav navbar-right">
				<li><%= link_to "#{current_user.name}", current_user %></li>
				<li><%= link_to "Users", users_path %></li>
				<li><%= link_to "Events", events_path %></li>
				<li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
			</ul>
		<% else %>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Sign In", signin_path %></li>
				<li><%= link_to "Sign Up", signup_path %></li>
			</ul>
		<% end %>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>PrivateEvents</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
	  <div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/shared/_table.html.erb
<table class="table">
	<thead>
		<tr>
			<td class="col-sm-3">Title</td>
			<td class="col-sm-4">Date </td>
			<td class="col-sm-3">Host </td>
		</tr>
	</thead>
 <ul>
<% if object.empty? %>
<tr>
	<td> None </td>
	<td> None </td>
	<td> None </td>
</tr>
<% else %>
	<% object.each do |event| %>
	<tr>
		<td> <%= link_to "#{event.title}", event_path(event) %></td>
		<td> <%= event.date.strftime("%B %d, %Y") %></td>
		<td> <%= link_to "#{event.creator.name}", user_path(event.creator) %> </td>
	</tr>
	<% end %>
<% end %>
</table>

app/views/users/index.html.erb
<h1> All Users </h1>
<table class = "table table-striped">
	<thead>
		<tr>
			<td class="col-sm-3">Name</td>
			<td class="col-sm-3">Email</td>
		</tr>
	</thead>
<% @users.each do |user| %>
<tr>

	<td> <%= link_to "#{user.name}", user_path(user[:id])%> </td>
	<td> <%= user.email %> </td>
</tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.email_field :email %>

			<%= f.submit "Create Account", class: "btn btn-success" %>

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>
<h2> <%= @user.email %> </h2> 

<h4> Created Events </h4>
<%= render 'shared/table', object: @created_events %>


<h4> Upcoming Events </h4>
<%= render 'shared/table', object: @upcoming_events %>

<h4> Previous Events </h4>
<%= render 'shared/table', object: @prev_events %>